export interface Post {
  slug: string
  stamp: string
  date: string
  readTime: string
  category: string
  title: string
  seoTitle: string
  deck: string
  variant: string
  featured?: boolean
  external?: boolean
  ogImage?: string
  dateModified?: string
  author?: string
}

export const posts: Post[] = [
  {
      slug: 'how-to-advertise-business-mallorca',
      stamp: 'DEC 15',
      date: 'Dec 15, 2026',
      readTime: '13 min',
      category: 'Local SEO',
      title: 'How to Advertise Your Business in Mallorca — The Complete Guide',
      seoTitle: 'How to Advertise a Business in Mallorca — The Complete Guide | pmax',
      deck: 'Mallorca has 900,000 permanent residents and nearly 10 million visitors a year. German tourists alone spend €1,200 per trip on average. This is the complete paid advertising guide for Mallorca businesses — every major channel, with specific budgets and market context that generic guides skip.',
      variant: 'is-yellow',
    },
  {
      slug: 'was-kostet-google-ads',
      stamp: 'DEC 01',
      date: 'Dec 1, 2026',
      readTime: '12 min',
      category: 'Google Ads',
      title: 'Google Ads Cost Guide 2026: What You Actually Pay',
      seoTitle: 'How Much Does Google Ads Cost in 2026? Honest Pricing Guide | pmax',
      deck: 'An honest, specific guide to Google Ads costs in 2026. Average CPCs by industry in Germany, the total cost equation, three budget scenarios — and a Palma estate agency that cut cost per lead from €200 to €83.',
      variant: 'is-slate',
    },
  {
    slug: 'conversion-rate-optimisation-checklist',
    stamp: 'NOV 17',
    date: 'Nov 17, 2026',
    readTime: '11 min',
    category: 'Web design',
    title: 'Conversion Rate Optimisation Checklist 2026: 15 Points That Move the Number',
    seoTitle: 'Conversion Rate Optimisation Checklist 2026 — 15-Point CRO Guide | pmax',
    deck: "A practical 15-point CRO checklist for business owners and marketers. Industry benchmarks, quick wins, structural fixes, and a real case: 28 to 71 qualified leads per month without changing the ad budget.",
    variant: 'is-mint',
  },
  {
      slug: 'what-is-generative-engine-optimisation',
      stamp: 'NOV 03',
      date: 'Nov 3, 2026',
      readTime: '11 min',
      category: 'AI search',
      title: 'What Is Generative Engine Optimisation (GEO)?',
      seoTitle: 'What Is Generative Engine Optimisation (GEO)? The Definitive Guide | pmax',
      deck: 'GEO is not SEO with a new name. It is a different discipline built for AI-generated answers — and research shows specific techniques can boost your citation rate by up to 40%. This is the complete guide, including an 8-step implementation framework.',
      variant: 'is-mint',
      author: 'Claire Enders',
      ogImage: '/blog/crunchjunkie-geo-audit-score.jpg',
    },
  {
    slug: 'performance-marketing-agency-vs-in-house',
    stamp: 'OCT 27',
    date: 'Oct 27, 2026',
    readTime: '10 min',
    category: 'Op-ed',
    title: 'Performance Marketing Agency vs. In-House Team: Our Honest View',
    seoTitle: 'Performance Marketing Agency vs. In-House Team — An Honest Guide | pmax',
    deck: "Most agencies will tell you to hire an agency. We will not always. Here is an honest breakdown of the real costs, the break-even point, and when building in-house is the right call.",
    variant: 'is-outlined',
  },
  {
    slug: 'linkedin-ads-b2b-spain',
    stamp: 'OCT 20',
    date: 'Oct 20, 2026',
    readTime: '10 min',
    category: 'LinkedIn',
    title: 'LinkedIn Ads for B2B in Spain: CPL benchmarks, targeting and what actually works',
    seoTitle: 'LinkedIn Ads B2B Spain — CPL Benchmarks & Targeting | pmax',
    deck: 'CPL benchmarks by industry for Spain, the LinkedIn targeting checklist, and a Palma law firm that cut cost per lead from €184 to €67 in 16 weeks.',
    variant: 'is-blue',
  },
  {
    slug: 'google-shopping-kampagne-leitfaden',
    stamp: 'OCT 13',
    date: 'Oct 13, 2026',
    readTime: '10 min',
    category: 'Google Ads',
    title: 'Google Shopping campaigns in 2026: the setup guide that skips the basics',
    seoTitle: 'Google Shopping 2026 — Setup Guide & ROAS Benchmarks | pmax',
    deck: 'Standard Shopping vs. Performance Max, feed requirements for Google Merchant Center, and ROAS benchmarks by e-commerce category — a 2026 setup guide.',
    variant: 'is-yellow',
  },
  {
    slug: 'tiktok-ads-mallorca-tourism',
    stamp: 'OCT 06',
    date: 'Oct 6, 2026',
    readTime: '9 min',
    category: 'Paid social',
    title: 'TikTok Ads for hospitality and tourism in Mallorca: what actually works',
    seoTitle: 'TikTok Ads Mallorca Tourism — A Practical Guide | pmax',
    deck: 'CPM benchmarks, creative formats, and the demographic breakdown that turns Mallorca tourism content into real charter and hotel bookings on TikTok.',
    variant: 'is-violet',
  },
  {
      slug: 'ki-sichtbarkeit-ai-visibility',
      stamp: 'SEP 22',
      date: 'Sep 22, 2026',
      readTime: '11 min',
      category: 'AI search',
      title: 'How to Get Your Brand Cited by AI Engines',
      seoTitle: 'AI Search Visibility: How to Get Cited by ChatGPT, Perplexity & Gemini | pmax',
      deck: "Most brands have no idea what ChatGPT says about them — or why. The data-backed guide to AI search visibility: how citation works, which levers move it, and what our own numbers look like across 10 engines.",
      variant: 'is-mint',
      author: 'Claire Enders',
      ogImage: '/blog/crunchjunkie-dashboard-visibility-sample-size.jpg',
    },
  {
    slug: 'meta-ads-agency-vs-in-house',
    stamp: 'SEP 15',
    date: 'Sep 15, 2026',
    readTime: '9 min',
    category: 'Paid social',
    title: 'Meta Ads agency vs. managing in-house: an honest comparison',
    seoTitle: 'Meta Ads Agency vs In-House — Real Costs & ROAS | pmax',
    deck: 'Agency retainer vs. in-house hire vs. freelancer: actual costs, realistic ROAS benchmarks, and when each option wins. Based on real hospitality accounts.',
    variant: 'is-slate',
  },
  {
    slug: 'free-website-design',
    stamp: 'SEP 08',
    date: 'Sep 8, 2026',
    readTime: '9 min',
    category: 'Web design',
    title: "We'll rebuild your website for free. Here's exactly what we get in return.",
    seoTitle: "Free Website Design & Rebuild — How pmax Does It | pmax",
    deck: "We redesign and rebuild websites at no upfront cost. In exchange, we take over your paid advertising. This is the full deal — how it works, who it's for, and what a real rebuild looks like.",
    variant: 'is-mint',
    featured: true,
  },
  {
    slug: 'ai-visibility-tracking-tools-2026',
    stamp: 'AUG 27',
    date: 'Aug 27, 2026',
    dateModified: 'Aug 28, 2026',
    readTime: '12 min',
    category: 'AI search',
    title: 'AI Visibility Tracking in 2026: What to Check Before You Sign Up',
    seoTitle: 'AI Visibility Tracking Tools 2026 — A Buyer\'s Guide | pmax',
    deck: 'How most AI visibility tools quietly limit what you can track — and what to ask before you pay for one. A buyer\'s guide with verified pricing.',
    variant: 'is-mint',
    featured: true,
    author: 'Claire Enders',
    ogImage: '/og/crunchjunkie-dashboard.jpg',
  },
  {
    slug: 'google-ads-ai-disclosure-label',
    stamp: 'AUG 26',
    date: 'Aug 26, 2026',
    readTime: '7 min',
    category: 'Google Ads',
    title: "Google's AI label is on your ads. You probably didn't decide that.",
    seoTitle: "Google Ads AI Disclosure Label — What PMax Advertisers Need to Know | pmax",
    deck: "Google now labels ads 'created or edited with AI' on European SERPs. Most advertisers who have it didn't consciously opt in — Performance Max did it for them.",
    variant: 'is-slate',
    featured: true,
    ogImage: '/og/google-ads-ai-disclosure-serp.jpg',
  },
  {
    slug: 'what-is-a-geo-audit',
    stamp: 'AUG 8',
    date: 'Aug 8, 2026',
    readTime: '10 min',
    category: 'AI search',
    title: 'What Is a GEO Audit — And How to Run One',
    seoTitle: 'What Is a GEO Audit? A Practical Guide | pmax',
    deck: "A GEO audit tells you what ChatGPT, Perplexity and Gemini say about your brand — and where they're getting it wrong. Here's how to run one.",
    variant: 'is-mint',
    featured: true,
    ogImage: '/og/geo-audit.webp',
  },
  {
    slug: 'perplexity-visibility',
    stamp: 'JUN 23',
    date: 'Jun 23, 2026',
    readTime: '8 min',
    category: 'AI search',
    title: 'How to Improve Your Perplexity Visibility (and Why It\'s Not ChatGPT)',
    seoTitle: 'How to Improve Your Perplexity Visibility | pmax',
    deck: "A plain-English guide to Perplexity visibility in 2026 — what it is, why it's different from ChatGPT, and five moves to get your business cited.",
    variant: 'is-mint',
    featured: true,
  },
  {
    slug: 'performance-max-bidding-change-august-2026',
    stamp: 'JUN 17',
    date: 'Jun 17, 2026',
    readTime: '8 min',
    category: 'Google Ads',
    title: 'Performance Max bidding changes on August 17. What to do before it lands.',
    seoTitle: 'Performance Max Bidding Changes on 17 August: What to Do First | pmax',
    deck: "Google's 17 August bidding change pulls over-performing Performance Max campaigns back toward target — automatically. Here's what to do before it lands.",
    variant: 'is-slate',
    featured: true,
    ogImage: '/og/performance-max-bidding-change-august-2026.jpg',
  },
  {
    slug: 'pinterest-ads-home-interiors-local-2026',
    stamp: 'JUN 01',
    date: 'Jun 1, 2026',
    readTime: '11 min',
    category: 'Paid social',
    title: 'Pinterest Ads in 2026: who can actually run them — and who should.',
    seoTitle: 'Pinterest Ads 2026: who can run them, and who should | pmax',
    deck: 'Who Pinterest Ads work for, how retargeting really works, and why a local window-coverings showroom is closer to its sweet spot than most ecommerce.',
    variant: 'is-pink',
    featured: true,
  },
  {
    slug: 'google-ads-vs-meta-ads-vs-tiktok-ads-ecommerce-2026',
    stamp: 'MAY 26',
    date: 'May 26, 2026',
    readTime: '14 min',
    category: 'Paid media',
    title: 'Google Ads vs Meta Ads vs TikTok Ads for ecommerce in 2026.',
    seoTitle: 'Google Ads vs Meta Ads vs TikTok Ads for Ecommerce 2026 | pmax',
    deck: 'A brutally practical, side-by-side comparison of the three biggest paid channels for ecommerce in 2026 — based on €2.1M of pmax-managed spend in Q1.',
    variant: 'is-slate',
    featured: true,
  },
  {
    slug: 'how-to-get-mentioned-by-chatgpt',
    stamp: 'APR 04',
    date: 'Apr 4, 2026',
    readTime: '9 min',
    category: 'AI search',
    title: 'How to get your business mentioned by ChatGPT, Perplexity and Gemini',
    seoTitle: 'How to get cited by ChatGPT, Perplexity & Gemini | pmax',
    deck: 'A plain-English guide to AI search visibility in 2026 — what it is, why it matters, and five things any business can start doing this month.',
    variant: 'is-mint',
    featured: true,
  },
  {
    slug: 'performance-max-2026',
    stamp: 'MAR 28',
    date: 'Mar 28, 2026',
    readTime: '7 min',
    category: 'Google Ads',
    title: "Performance Max in 2026: what's changed, and what we actually do now",
    seoTitle: 'Performance Max 2026 — what changed, what we do now | pmax',
    deck: 'A practical walkthrough of the seven Performance Max settings we change first on every new client account.',
    variant: 'is-outlined',
  },
  {
    slug: 'tracking-setup-guide',
    stamp: 'MAR 20',
    date: 'Mar 20, 2026',
    readTime: '11 min',
    category: 'Analytics',
    title: 'A no-jargon guide to setting up marketing tracking properly',
    seoTitle: 'No-jargon guide to marketing tracking setup | pmax',
    deck: 'Why most dashboards lie a little, where the discrepancy usually comes from, and how to get tracking right so the numbers match your bank account.',
    variant: 'is-violet',
  },
  {
    slug: 'meta-creative-volume',
    stamp: 'MAR 12',
    date: 'Mar 12, 2026',
    readTime: '8 min',
    category: 'Paid social',
    title: "Meta says creative is 56% of performance. Here's how to actually ship that much creative.",
    seoTitle: 'How to ship enough Meta creative for paid performance | pmax',
    deck: "A weekly creative production system that runs without burning your designers out — and the templates we use to scale it.",
    variant: 'is-slate',
  },
  {
    slug: 'google-ads-mallorca',
    stamp: 'MAR 06',
    date: 'Mar 6, 2026',
    readTime: '6 min',
    category: 'Local SEO',
    title: 'How to win Google Ads when your customers live in Mallorca and your competitors live abroad',
    seoTitle: 'Google Ads Mallorca — local targeting guide | pmax',
    deck: 'Geo-targeting, language signals, local conversion tracking and the small settings that make a big difference for Balearic businesses.',
    variant: 'is-yellow',
  },
  {
    slug: 'shopify-seo-2026',
    stamp: 'FEB 26',
    date: 'Feb 26, 2026',
    readTime: '10 min',
    category: 'SEO',
    title: 'Shopify SEO in 2026: the eight changes worth making this quarter',
    seoTitle: 'Shopify SEO in 2026 — the eight changes worth making | pmax',
    deck: 'Most Shopify stores leak SEO value by default. The handful of theme and structure fixes that move organic traffic the most.',
    variant: 'is-pink',
  },
  {
    slug: 'b2b-linkedin-playbook',
    stamp: 'FEB 18',
    date: 'Feb 18, 2026',
    readTime: '9 min',
    category: 'LinkedIn',
    title: 'The B2B LinkedIn playbook we ship to every new SaaS client',
    seoTitle: 'B2B LinkedIn playbook for SaaS — our day-one setup | pmax',
    deck: "Conversation ads, lead scoring, CRM-fed offline conversions, and the cadence of creative that actually keeps a B2B account fresh.",
    variant: 'is-blue',
  },
  {
    slug: 'cookieless-tracking',
    stamp: 'FEB 10',
    date: 'Feb 10, 2026',
    readTime: '12 min',
    category: 'Privacy',
    title: 'Cookieless tracking is here. Most marketers are not ready.',
    seoTitle: 'Cookieless tracking in 2026 — what changed and how to fix it | pmax',
    deck: "What Consent Mode v2, server-side tagging and the end of third-party cookies mean for your conversion data — and what to do about it.",
    variant: 'is-orange',
  },
  {
    slug: 'hotel-direct-bookings',
    stamp: 'FEB 02',
    date: 'Feb 2, 2026',
    readTime: '7 min',
    category: 'Hospitality',
    title: 'How a Mallorca hotel grew direct bookings 52% in 11 weeks',
    seoTitle: 'Mallorca hotel — +52% direct bookings in 11 weeks | pmax',
    deck: "A short case-style write-up on what Mar y Roca did to break their dependence on Booking.com, and how much it actually saved them.",
    variant: 'is-mint',
  },
  {
    slug: 'real-estate-lead-gen',
    stamp: 'JAN 26',
    date: 'Jan 26, 2026',
    readTime: '8 min',
    category: 'Real estate',
    title: "Real estate lead generation in 2026: why your form is the problem",
    seoTitle: 'Real estate lead gen — why your form loses 80% of leads | pmax',
    deck: "Most real estate websites lose 80% of motivated buyers at the form. Five fixes that work for Mallorca agencies — and ten others.",
    variant: 'is-outlined',
  },
  {
    slug: 'tiktok-organic-paid',
    stamp: 'JAN 18',
    date: 'Jan 18, 2026',
    readTime: '6 min',
    category: 'Paid social',
    title: "TikTok's organic-paid loop: what's actually working in 2026",
    seoTitle: "TikTok organic-paid loop — what's working in 2026 | pmax",
    deck: "The three TikTok content patterns that earn impressions and the paid setup we layer on top to compound them into revenue.",
    variant: 'is-violet',
  },
  {
    slug: 'solar-marketing-spain',
    stamp: 'JAN 10',
    date: 'Jan 10, 2026',
    readTime: '9 min',
    category: 'Renewables',
    title: 'Solar marketing in Spain: the unsexy work that moves the needle',
    seoTitle: 'Solar marketing in Spain — what actually works | pmax',
    deck: "Why most solar installers lose money on Meta — and the funnel structure that turns a €40 click into a €6,000 install.",
    variant: 'is-slate',
  },
  {
    slug: 'creative-testing-framework',
    stamp: 'DEC 18',
    date: 'Dec 18, 2025',
    readTime: '8 min',
    category: 'Creative',
    title: 'A creative testing framework that actually compounds',
    seoTitle: 'A creative testing framework that actually compounds | pmax',
    deck: "How to test ad creative so you build a library of winners — not just a graveyard of one-off launches.",
    variant: 'is-yellow',
  },
  {
    slug: 'gpt-shopping',
    stamp: 'DEC 08',
    date: 'Dec 8, 2025',
    readTime: '7 min',
    category: 'AI search',
    title: 'What "ChatGPT shopping" means for e-commerce brands in 2026',
    seoTitle: 'What ChatGPT shopping means for e-commerce in 2026 | pmax',
    deck: "OpenAI is quietly building a shopping interface inside ChatGPT. Here's how to make sure your products show up.",
    variant: 'is-pink',
  },
  {
    slug: 'ga4-mistakes',
    stamp: 'NOV 28',
    date: 'Nov 28, 2025',
    readTime: '10 min',
    category: 'Analytics',
    title: 'The seven GA4 setups we fix on every new client',
    seoTitle: 'The seven GA4 setups we fix on every new client | pmax',
    deck: "GA4 is fine. Most GA4 installations are not. The seven specific things we change in week one, every time.",
    variant: 'is-blue',
  },
  {
    slug: 'crm-conversion-imports',
    stamp: 'NOV 18',
    date: 'Nov 18, 2025',
    readTime: '9 min',
    category: 'Analytics',
    title: 'Stop optimising for form fills. Start optimising for revenue.',
    seoTitle: 'Stop optimising for form fills. Optimise for revenue. | pmax',
    deck: "Why importing offline conversions from your CRM is the single highest-leverage thing a B2B marketing team can do this year.",
    variant: 'is-orange',
  },
  {
    slug: 'yachting-marketing',
    stamp: 'NOV 04',
    date: 'Nov 4, 2025',
    readTime: '8 min',
    category: 'Boating',
    title: 'Marketing a yacht charter business: an eight-language, twelve-month problem',
    seoTitle: 'How to market a yacht charter business | pmax',
    deck: "How we plan media for a seasonal business with a six-figure average booking value and customers in three time zones.",
    variant: 'is-mint',
  },
  {
    slug: 'agency-pricing-honest',
    stamp: 'OCT 20',
    date: 'Oct 20, 2025',
    readTime: '5 min',
    category: 'Op-ed',
    title: 'Why we charge flat fees, not a percentage of media spend',
    seoTitle: "Why we charge flat fees, not a % of media spend | pmax",
    deck: "A short note on the perverse incentives most agencies operate under — and why we don't.",
    variant: 'is-outlined',
  },
]

export function getPost(slug: string) {
  return posts.find(p => p.slug === slug)
}
